---
title: "Summer Matching project"
author: "Bhumpanya Chaisrisawatsuk"
date: "2024-06-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("/Users/bhumpanya/Documents/Greg Jefferis' lab/R/NBLAST matching")
```

```{r}
#load libraries
library(arrow)
library(dplyr)
library(malecns)
library(fafbseg)
library(googlesheets4)
library(tidyverse)
```

```{r}
ac_match <- arrow::read_feather("/Users/bhumpanya/Documents/Greg Jefferis' lab/R/NBLAST matching/whole_central_20240621_faq_nbl_export_matches.20240626T0830.lz4.feather")
colnames(ac_match) <- c("nblast_match", "conn_match", "mcns_id")
```

```{r}
info = flytable_list_rows('info', chunksize = 10000)
```

```{r}
infof <- info %>% 
  filter(!duplicated(root_783)) %>% 
  select(cell_type, root_783, ito_lee_hemilineage, hartenstein_hemilineage, side, malecns_type, hemibrain_type)

infof_ac <- infof[infof$root_783 %in% ac_match$conn_match | infof$root_783 %in% ac_match$nblast_match,]
```

```{r}
merged_df <- merge(ac_match, infof_ac, by.x = "conn_match", by.y = "root_783", all.x = TRUE)
# Add suffix to the columns from infof_ac
infof_ac_columns <- setdiff(names(infof_ac), "root_783") # Exclude the join column
new_names <- paste0(infof_ac_columns, "_conn") # Add suffix to the columns
names(merged_df)[names(merged_df) %in% infof_ac_columns] <- new_names 

merged_df_new <- merge(merged_df, infof_ac, by.x = "nblast_match", by.y = "root_783", all.x = TRUE)
infof_ac_columns <- setdiff(names(infof_ac), "root_783") 
new_names <- paste0(infof_ac_columns, "_nblast") 
names(merged_df_new)[names(merged_df_new) %in% infof_ac_columns] <- new_names 
```

```{r}
malecns_info <- mcns_body_annotations()
malecns_info_f <- malecns_info[malecns_info$bodyid %in% ac_match$mcns_id,]
malecns_info_f <- malecns_info_f %>% select(bodyid, type, flywire_type, hemibrain_type, soma_side) 

merged_df_newer <- merge(merged_df_new, malecns_info_f, by.x = "mcns_id", by.y = "bodyid", all.x = TRUE)
```

```{r}
same_match <- merged_df_newer[merged_df_newer$nblast_match == merged_df_newer$conn_match,]

same_match$male_hemilineage = NA
same_match$male_hemilineage = ifelse(same_match$cell_type_conn == same_match$type, same_match$ito_lee_hemilineage_conn, NA)

same_match$male_hart_hemilineage = ifelse(same_match$cell_type_conn == same_match$type, same_match$hartenstein_hemilineage_conn, NA)
```

```{r}
lf_match <- arrow::read_feather("/Users/bhumpanya/Documents/Greg Jefferis' lab/R/NBLAST matching/matches_mcns_left_right.feather")
opposite <- c(14659, 18181, 24856, 32855, 34185, 37841, 50226, 57667, 73439, 78293, 78807, 86259, 102607, 109149, 113918, 140957, 148690, 513791, 520021)
lf_match_1 <- lf_match %>% 
  select(id,match_1)
lf_match_1_opp <- lf_match_1[lf_match_1$id %in% opposite,]
lf_match_1_opp %>% select(match_1) %>% clipr::write_clip()
```

```{r}
malecns_info_side <- malecns_info %>% select(bodyid, soma_side)
neurotype <- c(10573, 12130, 12424, 12458, 13697, 13974, 14980, 15340, 15471, 15508, 16775, 18078, 18518, 18917, 19120, 19350, 19537, 19540, 19659, 19667, 19703, 20112, 20378, 20933, 21065, 21173, 21199, 21238, 21426, 21632, 21744, 21835, 21983, 21984, 22070, 22148, 22184, 22248, 22259, 22339, 22392, 22397, 22505, 22510, 22750, 22783, 22831, 22959, 22989, 22997, 23001, 23002, 23128, 23148, 23154, 23210, 23328, 23377, 23421, 23463, 23499, 23599, 23677, 23686, 23719, 23741, 23830, 23852, 23867, 23868, 23890, 23930, 23989, 24035, 24071, 24164, 24208, 24211, 24283, 24482, 24492, 24505, 24545, 24592, 24719, 24742, 24769, 24784, 24854, 24909, 25003, 25067, 25088, 25167, 25198, 25202, 25296, 25304, 25369, 25394, 25400, 25412, 25446, 25450, 25472, 25641, 25711, 25817, 25952, 26142, 26373, 26380, 26450, 26560, 26740, 26788, 26811, 26963, 26976, 27067, 27300, 27334, 27468, 27579, 27689, 27704, 27709, 27915, 27967, 28082, 28143, 28204, 28259, 28390, 28533, 28543, 28599, 28654, 28823, 28904, 29092, 29186, 29359, 29686, 29744, 29803, 29979, 30025, 30499, 30707, 30993, 31033, 31250, 31623, 31634, 31801, 31878, 31941, 31976, 32090, 32111, 32153, 32238, 32286, 32336, 32493, 32614, 32657, 32767, 32946, 33048, 33177, 33219, 34351, 34643, 34756, 34774, 34838, 35250, 36152, 36286, 36421, 36779, 36783, 37042, 37316, 37871, 37896, 37958, 38020, 38301, 38374, 38810, 39108, 40220, 40815, 41089, 41240, 42379, 42452, 43865, 43910, 44299, 44656, 44666, 44856, 45300, 45579, 46034, 47206, 47400, 48198, 48716, 48790, 49244, 49360, 49424, 49773, 49807, 50564, 51397, 51462, 51720, 52329, 52430, 52783, 53572, 53585, 54421, 54562, 54638, 56376, 57264, 57894, 58449, 60028, 60207, 61545, 62280, 64964, 66361, 68463, 68728, 69463, 69870, 70408, 73715, 74072, 76174, 76185, 82439, 84104, 84470, 85707, 86507, 87750, 89301, 100368, 140676, 144957, 183483, 512978, 514646, 518681, 519168, 524616, 525482, 527684, 528991, 529578, 532298, 532653, 536318, 557990, 575597)
ss_match <- malecns_info_side[malecns_info_side$bodyid %in% neurotype,]
ss <- ss_match[order(ss_match[,1], decreasing = FALSE),]
ss %>% select(soma_side) %>% clipr::write_clip()
```

```{r}
ss_ss <- ss_match %>% filter(soma_side == "L")
ss_ss %>% select(bodyid) %>% clipr::write_clip()
```

```{r}
neurotype <- mba %>% filter(hemilineage == "putative_primary") %>% select(bodyid, soma_side)
neurotype_ss <- neurotype %>% filter(soma_side == "L") %>% select(bodyid) %>% clipr::write_clip()
```

```{r}
match_side <- merge(lf_match, malecns_info_side, by.x = "id", by.y = "bodyid", all.y = T)
```

```{r}
a <- c("720575940618984475", "720575940629401674", "720575940634866586", "720575940646310947", "720575940646518382")
a %>% clipr::write_clip()
```

```{r}
neurotype <- c(12308, 12712, 12798, 12848, 13354, 13603, 14002, 14082, 14828, 15031, 15642, 15787, 15792, 16313, 16319, 16590, 16748, 17148, 17338, 17451, 17486, 17678, 17708, 17810, 17813, 18341, 18369, 18471, 18969, 19129, 19152, 19552, 20038, 20042, 20193, 20207, 20229, 20369, 20410, 20479, 21000, 21203, 21217, 21642, 21964, 22071, 22199, 22331, 22333, 22403, 22410, 22777, 22912, 23049, 23243, 23356, 23445, 23681, 23742, 23901, 23920, 23921, 23922, 23927, 24036, 24068, 24608, 24782, 24787, 24991, 25026, 25135, 25235, 25707, 25774, 26057, 26122, 26183, 26403, 26654, 26799, 26938, 27038, 27456, 27493, 27562, 27708, 27910, 28568, 28597, 28703, 29120, 29524, 30065, 30070, 30736, 30778, 31107, 31152, 31787, 31811, 32399, 32602, 32644, 32869, 33160, 33402, 33423, 33518, 34071, 34396, 35056, 35201, 35516, 36958, 36975, 37133, 37434, 37593, 37864, 38190, 38662, 38694, 38879, 39044, 40193, 40575, 40684, 40926, 41697, 42381, 43261, 43644, 44059, 44273, 44886, 45362, 45682, 45829, 46321, 46792, 47175, 47553, 47682, 48493, 48610, 49012, 49947, 50017, 50611, 50662, 50688, 51584, 51900, 51983, 52308, 52371, 52806, 53272, 53466, 53540, 54174, 54204, 54925, 55287, 55793, 55852, 56140, 56395, 57074, 57346, 58630, 58737, 60509, 60685, 60837, 62400, 63008, 63309, 63545, 63671, 64584, 65069, 65078, 66523, 67695, 68356, 69529, 70480, 70617, 72481, 72870, 72927, 74049, 74335, 74987, 76141, 76475, 77114, 77709, 79264, 79715, 81703, 85485, 85839, 86452, 86737, 89857, 90956, 94811, 173417, 200843, 228169, 518506, 525524, 536934, 537803, 575643, 575755, 584042, 588399, 915560, 919294, 919295)
hemilineage <- c(12308, 12798, 12848, 13354, 13603, 14082, 15031, 15787, 15792, 16313, 16319, 17338, 17451, 17486, 17678, 17708, 17810, 17813, 18341, 18369, 18471, 18969, 19129, 19152, 19552, 20042, 20193, 20207, 20229, 20479, 21000, 21203, 21217, 21642, 21964, 22071, 22199, 22331, 22333, 22410, 22777, 22912, 23049, 23243, 23445, 23681, 23742, 23901, 23920, 23922, 23927, 24782, 24787, 25026, 25235, 25774, 26122, 26183, 26403, 26654, 26799, 26938, 27456, 27493, 27562, 27708, 27910, 28568, 28597, 28703, 29120, 29524, 30065, 30070, 30778, 31152, 31787, 32602, 32644, 32869, 33423, 34071, 34396, 35201, 36958, 36975, 37133, 37434, 37864, 38662, 40926, 45362, 47682, 48610, 50611, 51983, 52308, 52371, 52806, 55287, 70480, 72870, 72927, 74987, 76141, 76475, 94811, 228169, 525524, 536934, 588399)
unhemilineage <- setdiff(neurotype, hemilineage)
a <- length(unhemilineage)
v <- NULL
for (i in a)
{
  v <- c(v,'lateral')
}
unhemilineage_hemilineage <- cbind(unhemilineage, v)
b <- length(hemilineage)
w <- NULL
for (i in b)
{
  w <- c(w,'anterior')
}
hemilineage_hemilineage <- cbind(hemilineage, w)
neurotype_hemilineage <- rbind(unhemilineage_hemilineage, hemilineage_hemilineage)
colnames(neurotype_hemilineage) <- c('bodyid','hemilineage')
neurotype_hemilineage %>% clipr::write_clip()
```


```{r}
a <- c(11623, 13788, 14052, 14751, 14817, 15026, 15445, 15698, 15714, 15765, 15885, 16125, 16254, 16641, 17275, 17903, 17953, 18146, 20096, 20447, 20582, 20922, 21162, 22315, 23143, 23509, 23536, 25023, 25755, 26179, 26199, 26320, 27776, 28227, 28709, 28922, 29534, 29622, 29987, 30900, 31058, 32894, 33122, 34350, 34357, 35228, 35728, 36047, 36409, 36878, 37920, 38222, 39786, 41631, 42774, 44197, 45806, 46223, 46668, 49548, 52366, 53403, 54247, 54333, 54381, 54537, 56452, 57786, 58531, 59525, 61578, 62916, 63680, 64429, 65207, 66127, 67228, 70540, 71581, 71967, 72181, 74503, 75501, 75874, 78944, 81760, 82623, 82845, 83402, 83696, 84143, 84547, 86368, 87420, 87455, 87708, 89201, 90422, 92053, 93468, 95645, 95863, 96458, 98157, 98336, 99646, 99855, 101349, 101584, 103476, 104089, 104141, 104499, 104531, 104734, 104954, 105556, 106388, 107544, 108026, 109830, 109887, 109931, 110388, 110821, 111796, 112897, 114443, 114507, 115340, 116584, 118996, 119700, 120181, 120564, 121755, 122434, 122986, 123464, 124421, 124940, 126332, 126923, 127917, 128709, 129234, 129948, 131000, 131221, 131775, 132110, 132353, 132840, 133821, 134610, 134832, 134842, 136095, 136729, 137543, 138380, 138655, 138925, 139777, 140612, 141224, 141515, 141537, 141703, 141870, 144787, 145062, 145613, 146121, 146574, 146588, 146693, 147920, 148381, 148711, 148787, 148891, 149284, 150106, 151629, 152095, 152450, 152644, 152746, 153054, 154080, 154478, 155663, 156004, 156429, 156491, 156568, 156962, 158296, 158635, 158782, 158930, 159363, 159532, 159589, 160349, 160420, 161592, 161856, 163096, 163238, 164401, 165116, 165612, 165864, 167420, 168711, 169003, 169799, 172928, 173705, 174318, 175681, 175831, 177757, 180341, 180654, 184913, 187891, 187933, 188890, 193932, 195691, 196579, 200117, 201088, 201295, 201983, 205453, 213941, 222298, 239218, 240951, 256206, 513099, 513158, 513794, 514600, 516360, 516429, 516653, 517110, 517684, 518549, 518657, 519927, 520905, 521261, 523044, 523568, 524372, 524646, 525279, 526857, 529235, 529959, 530148, 530156, 543906, 550121, 555277, 555278, 557095, 559506, 560842, 565505, 569702, 570035, 580144, 581324)
b <- c(12311, 14652, 15026, 15929, 16126, 16285, 16908, 17341, 17639, 17953, 18112, 18666, 19266, 19373, 19460, 21053, 21700, 22291, 22434, 22700, 22844, 22929, 23473, 23596, 23831, 24291, 25318, 26065, 26199, 27430, 27730, 28227, 28286, 29152, 29582, 29622, 29921, 30927, 32743, 32976, 33919, 34350, 34909, 34962, 35400, 35597, 36047, 36785, 37039, 37920, 38182, 39091, 39336, 39465, 40458, 41331, 41544, 41554, 43909, 44139, 44675, 45806, 46008, 46223, 46369, 46636, 46943, 47546, 47850, 47995, 48421, 48448, 49226, 49620, 50733, 51168, 52063, 52397, 52571, 53017, 53467, 53991, 55161, 55953, 56350, 56567, 57278, 58552, 59485, 59525, 59550, 60711, 61025, 61392, 61871, 62020, 63068, 63122, 63639, 64163, 65047, 65705, 65822, 66165, 66695, 66977, 67116, 67241, 67703, 68268, 68672, 69684, 70139, 70573, 71433, 71769, 72963, 73112, 73808, 75125, 75614, 75864, 76200, 78294, 78577, 79273, 79427, 79948, 81047, 81265, 81303, 82111, 82261, 82623, 83070, 83247, 83319, 83388, 83467, 83676, 84083, 84143, 84191, 84217, 84305, 84661, 84836, 84895, 86425, 87121, 87524, 87712, 87720, 89155, 89937, 91507, 91930, 92564, 92576, 92734, 92836, 92841, 93555, 94528, 94739, 94984, 96745, 97375, 98899, 100456, 100788, 101138, 102878, 103686, 104155, 104203, 104954, 105436, 105479, 105556, 106168, 106414, 106493, 106593, 108026, 108216, 108585, 108860, 109306, 109830, 109931, 110821, 110924, 111206, 113184, 113588, 115153, 115340, 115824, 116200, 117269, 118234, 119244, 119860, 121507, 121970, 122434, 122823, 123635, 124000, 126412, 126806, 129597, 129625, 130175, 130382, 130735, 130784, 133153, 133222, 134266, 136667, 136890, 138727, 138739, 139067, 140766, 143540, 145109, 145366, 146260, 148097, 148115, 148244, 148694, 148789, 148852, 149536, 149714, 150434, 151411, 151423, 152294, 152435, 152450, 153303, 153474, 153589, 154070, 154636, 155526, 156074, 156988, 157644, 157821, 158606, 160484, 162211, 162457, 163533, 164589, 164652, 166246, 168875, 170454, 170639, 172625, 173250, 173705, 173845, 174318, 174657, 177926, 180341, 184913, 189323, 191694, 192829, 195276, 201088, 201131, 201160, 202114, 202360, 205526, 217561, 226132, 226303, 230132, 256361, 261819, 325193, 513177, 513376, 513662, 513804, 514601, 514689, 515194, 515739, 516079, 516360, 516429, 518451, 518644, 520903, 521975, 524646, 525393, 525448, 525604, 526857, 526973, 527427, 529126, 530340, 530506, 530855, 531914, 532124, 533123, 536058, 536441, 536443, 538118, 549582, 549816, 552128, 568738, 578189, 578449, 581235, 581422, 922814, 382559434)
i <- intersect(a,b)
print(i)
```
